import {ObjectType} from '../../enums/object-type.js';
import {ToolType} from '../../enums/tool-type.js';

export const objectLabels = Object.freeze({
    [ObjectType.Arrow]: 'arrow',
    [ObjectType.Bitmap]: 'legacy fill image',
    [ObjectType.Callout]: 'callout',
    [ObjectType.Comment]: 'comment',
    [ObjectType.Connector]: 'connector',
    [ObjectType.Diamond]: 'diamond',
    [ObjectType.Ellipse]: 'ellipse',
    [ObjectType.FlowDatabase]: 'database',
    [ObjectType.FlowDecision]: 'decision',
    [ObjectType.FlowProcess]: 'process',
    [ObjectType.FlowTerminator]: 'terminator',
    [ObjectType.Frame]: 'frame',
    [ObjectType.Freeform]: 'freeform shape',
    [ObjectType.Image]: 'image',
    [ObjectType.Label]: 'label',
    [ObjectType.Line]: 'line',
    [ObjectType.List]: 'list',
    [ToolType.Marker]: 'marker',
    [ObjectType.MindNode]: 'mind map node',
    [ObjectType.Path]: 'drawing',
    [ToolType.Pen]: 'pen',
    [ToolType.Pencil]: 'pencil',
    [ObjectType.Polygon]: 'polygon',
    [ObjectType.Rectangle]: 'rectangle',
    [ObjectType.Sticky]: 'note',
    [ObjectType.Swimlane]: 'swimlane',
    [ObjectType.Kanban]: 'kanban',
    [ObjectType.TemplateFrame]: 'template',
    [ObjectType.Text]: 'text',
});
