export const objectLabels = {
    arrow: 'arrow',
    bitmap: 'legacy fill image',
    callout: 'callout',
    comment: 'comment',
    connector: 'connector',
    diamond: 'diamond',
    ellipse: 'ellipse',
    'flow-database': 'database',
    'flow-decision': 'decision',
    'flow-process': 'process',
    'flow-terminator': 'terminator',
    frame: 'frame',
    freeform: 'freeform shape',
    image: 'image',
    label: 'label',
    line: 'line',
    list: 'list',
    marker: 'marker',
    'mind-node': 'mind map node',
    path: 'drawing',
    pen: 'pen',
    pencil: 'pencil',
    polygon: 'polygon',
    rectangle: 'rectangle',
    sticky: 'note',
    swimlane: 'swimlane',
    kanban: 'kanban',
    'template-frame': 'template',
    text: 'text',
};
