export const ActivityKind = Object.freeze({
    BoardCleared: 'board-cleared',
    CommentAdded: 'comment-added',
    FillUsed: 'fill-used',
    HistoryUsed: 'history-used',
    ImageImported: 'image-imported',
    ObjectDeleted: 'object-deleted',
    ObjectDuplicated: 'object-duplicated',
    ObjectLayered: 'object-layered',
    ObjectMoved: 'object-moved',
    ObjectResized: 'object-resized',
    ObjectRotated: 'object-rotated',
    ObjectStyled: 'object-styled',
    ObjectsGrouped: 'objects-grouped',
    ObjectsLocked: 'objects-locked',
    ObjectsUngrouped: 'objects-ungrouped',
    ObjectsUnlocked: 'objects-unlocked',
    ShapeAdded: 'shape-added',
    SnapshotCreated: 'snapshot-created',
    SnapshotRestored: 'snapshot-restored',
    StickyAdded: 'sticky-added',
    TextAdded: 'text-added',
    ToolUsed: 'tool-used',
    UserJoined: 'user-joined',
    UserLeft: 'user-left',
});
