import {ObjectType} from './object-type.js';

export const ToolType = Object.freeze({
    Arrow: ObjectType.Arrow,
    Callout: ObjectType.Callout,
    Comment: ObjectType.Comment,
    Connector: ObjectType.Connector,
    Diamond: ObjectType.Diamond,
    Ellipse: ObjectType.Ellipse,
    Eraser: 'eraser',
    Fill: 'fill',
    FlowDatabase: ObjectType.FlowDatabase,
    FlowDecision: ObjectType.FlowDecision,
    FlowProcess: ObjectType.FlowProcess,
    FlowTerminator: ObjectType.FlowTerminator,
    Frame: ObjectType.Frame,
    Freeform: ObjectType.Freeform,
    Hand: 'hand',
    Kanban: ObjectType.Kanban,
    Label: ObjectType.Label,
    Lasso: 'lasso',
    Laser: 'laser',
    Line: ObjectType.Line,
    List: ObjectType.List,
    Marker: 'marker',
    MindNode: ObjectType.MindNode,
    ObjectEraser: 'object-eraser',
    Pan: 'pan',
    Pen: 'pen',
    Pencil: 'pencil',
    Polygon: ObjectType.Polygon,
    Rectangle: ObjectType.Rectangle,
    Reaction: 'reaction',
    Select: 'select',
    Sticky: ObjectType.Sticky,
    Swimlane: ObjectType.Swimlane,
    TemplateArchitecture: 'template-architecture',
    TemplateBrainstorming: 'template-brainstorming',
    TemplateJourney: 'template-journey',
    TemplateRetro: 'template-retro',
    Text: ObjectType.Text,
});

export const DrawnShapeTools = Object.freeze([
    ToolType.Rectangle,
    ToolType.Ellipse,
    ToolType.Diamond,
    ToolType.Polygon,
    ToolType.Line,
    ToolType.Arrow,
    ToolType.Frame,
    ToolType.FlowProcess,
    ToolType.FlowDecision,
    ToolType.FlowTerminator,
    ToolType.FlowDatabase,
    ToolType.MindNode,
    ToolType.Swimlane,
    ToolType.Kanban,
    ToolType.TemplateRetro,
    ToolType.TemplateJourney,
    ToolType.TemplateArchitecture,
    ToolType.TemplateBrainstorming,
]);
